import { StreamVideoProvider } from "../providers/StreamVideoProvider";
import type { Metadata } from "next";
import { Toaster } from "../../@/components/ui/sonner";

export const metadata: Metadata = {
	title: "Calls & Chat | LinkedUp",
	description: "Generated by create next app",
};

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	
    return (
        <StreamVideoProvider>
            {children}
			<Toaster/>
        </StreamVideoProvider>

	);
}